image: golang:1.8rc3-alpine

variables:
  SRC:          /go/src/gitlab.com/Roman2K/scat
  MAIN_PACKAGE: ./cmd
  GOX_IMPORT:   github.com/mitchellh/gox
  GOX_REF:      c9740af9c6574448fd48eb30a71f964014c7a837

before_script:
  - apk update
  - apk add glide git bash findutils

  # gox
  - go get -d $GOX_IMPORT
  - cd /go/src/$GOX_IMPORT
  - git checkout $GOX_REF
  - go install

  # make available under $GOPATH
  - mkdir -p $(dirname $SRC)
  - ln -s "$CI_PROJECT_DIR" $SRC
  - cd $SRC
  - glide install

stages:
  - test
  - binaries

test:
  stage: test
  script:
    - cd $SRC
    - tools/test

binaries:
  stage: binaries
  only:
    - tags
  artifacts:
    paths:
      - scat-*.tar
  script:
    - cd $SRC
    - gox -output=".gox/{{.OS}}-{{.Arch}}/scat/scat" $MAIN_PACKAGE
    - cd .gox
    - ref=${CI_BUILD_TAG-${CI_BUILD_REF:0:8}}
    - for d in *; do (cd $d && tar cf ../../scat-${ref}-${d}.tar scat) || break; done
